### Кросс-валидация

#### Практическое задание для самостоятельного выполнения

**Задание 1.**

1. Сформировать текстовый файл, содержащий список группы с указанием для каждого студента имеется/не имеется задолженность за последнюю сессию (например, в формате 0/1). В списке должно быть не менее 15-20 записей. Импортировать эти данные в объект _Pandas DataFrame_.
* Create your own text file containing a list of students where it indicates for each student whether there is/is not failed examinations from the last semester (for example, in the format 0/1). The list should contain at least 20 students. Import this data into a _Pandas DataFrame_.
<br>

2. С полученным набором данных реализовать различные стратегии кросс-валидации и проанализировать полученные результаты.
* With the created DataFrame, implement these various cross-validation strategies and analyze the results:
<br>

    * 2.1. Применить стратегию _**KFold**_ с разбиением на 5 блоков без перемешивания. Вывести списки индексов объектов, попавших в обучающую и тестовую выборку на каждой итерации, и сформировать собственно обучающие и тестовые выборки (данные и метки классов).
    * 2.1. Apply the _**KFold**_ strategy with splitting into 5 blocks **without shuffling**. Display lists of indices of objects included in the training and test sets at each iteration, and form the actual training and test sets (data and class labels). 
<br><br>

    * 2.2. Применить стратегию _**KFold**_ с разбиением на 5 блоков с перемешиванием. Вывести списки индексов объектов, попавших в обучающую и тестовую выборку на каждой итерации, и сформировать собственно обучающие и тестовые выборки (данные и метки классов). Сравнить с результатами п. 2.1, дать объяснения. 
    * 2.2. Apply the _**KFold**_ strategy with splitting into 5 blocks **with shuffling**. Display lists of indices of objects included in the training and test sets at each iteration, and form the actual training and test sets (data and class labels). Compare with the results from 2.1 and give explanations.
<br><br>
    
    * 2.3. Применить стратегию _**StratifiedKFold**_ с разбиением на 5 блоков. Вывести списки индексов объектов, попавших в обучающую и тестовую выборку на каждой итерации, и сформировать собственно обучающие и тестовые выборки (данные и метки классов). Сравнить с результатами п. 2.1 и 2.2, дать объяснения.
    * 2.3. Apply the _**StratifiedKFold**_ strategy with splitting into 5 blocks. Display lists of indices of objects included in the training and test sets at each iteration, and form the actual training and test sets (data and class labels). Compare with the results from 2.1 and 2.2 and give explanations.
<br><br>
    
    * 2.4. Применить стратегию _**ShuffleSplit**_ с разбиением на 10 блоков. Вывести списки индексов объектов, попавших в обучающую и тестовую выборку на каждой итерации, и сформировать собственно обучающие и тестовые выборки (данные и метки классов). Сравнить с предыдущими результатами, дать объяснения.
    * 2.4. Apply the _**ShuffleSplit**_ strategy with splitting into 10 blocks. Display lists of indices of objects included in the training and test sets at each iteration, and form the actual training and test sets (data and class labels). Compare with previous results and give explanations.
<br><br>

    * 2.5. Применить стратегию _**StratifiedShuffleSplit**_ с разбиением на 10 блоков. Вывести списки индексов объектов, попавших в обучающую и тестовую выборку на каждой итерации, и сформировать собственно обучающие и тестовые выборки (данные и метки классов). Сравнить с результатами п. 2.4, дать объяснения. 
    * 2.5. Apply the _**StratifiedShuffleSplit**_ strategy with splitting into 10 blocks. Display lists of indices of objects included in the training and test sets at each iteration, and form the actual training and test sets (data and class labels). Compare with the results from 2.4 and give explanations.
<br><br>

    * 2.6. Применить стратегию _**LeaveOneOut**_. Вывести списки индексов объектов, попавших в обучающую и тестовую выборку на каждой итерации, и сформировать собственно обучающие и тестовые выборки (данные и метки классов).
    * 2.6. Apply the _**LeaveOneOut**_ strategy. Display lists of indices of objects included in the training and test sets at each iteration, and form the actual training and test sets (data and class labels).

In [ ]:
import pandas as pd
df = pd.read_csv('spisok_studentov.txt', sep='\t', header=0, encoding = 'UTF-8')
df

student  result
0       Craig Kennedy       1
1      Tania Thompson       1
2        Corinne Horn       0
3       Caitlyn Blake       1
4    Carleigh Stevens       0
5        Bella Barron       1
6         Jason Wolfe       0
7   Sullivan Alvarado       1
8            Lina Fry       1
9      Ainsley Ibarra       1
10     Jayleen Fuller       1
11      Solomon Olsen       1
12  Armani Valenzuela       0
13  Sofia Fitzpatrick       1
14        Amiah Sharp       1
15    Rohan Gillespie       1
16   Giovanny Whitney       1
17       Amari Powers       1
18      Conor Summers       0
19      Layne Ballard       0

In [ ]:
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import ShuffleSplit
from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.model_selection import LeaveOneOut

In [ ]:
X = df.index.to_numpy()
y = df.result.to_numpy()

print(X)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[1 1 0 1 0 1 0 1 1 1 1 1 0 1 1 1 1 1 0 0]


In [ ]:
X = df.index.tolist()
y = df.result.tolist()

print(X)
print(y)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
[1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0]


In [ ]:
# KFold с разбиением на 5 блоков без перемешивания

kf = KFold(n_splits=5, shuffle=False)

for train, test in kf.split(X, y):
    print(train, test)

[ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] [0 1 2 3]
[ 0  1  2  3  8  9 10 11 12 13 14 15 16 17 18 19] [4 5 6 7]
[ 0  1  2  3  4  5  6  7 12 13 14 15 16 17 18 19] [ 8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11 16 17 18 19] [12 13 14 15]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15] [16 17 18 19]


In [ ]:
# KFold с разбиением на 5 блоков с перемешиванием

kf = KFold(n_splits=5, shuffle=True)

for train, test in kf.split(X, y):
    print(train, test)

[ 1  2  3  4  5  7  8  9 10 11 12 14 15 16 18 19] [ 0  6 13 17]
[ 0  1  3  4  5  6  7  9 10 11 13 14 16 17 18 19] [ 2  8 12 15]
[ 0  2  3  4  6  8  9 10 12 13 14 15 16 17 18 19] [ 1  5  7 11]
[ 0  1  2  5  6  7  8 10 11 12 13 14 15 16 17 18] [ 3  4  9 19]
[ 0  1  2  3  4  5  6  7  8  9 11 12 13 15 17 19] [10 14 16 18]


In [ ]:
# StratifiedKFold с разбиением на 5 блоков
# for more details: https://russianblogs.com/article/9585922754/

skf = StratifiedKFold(n_splits=5)

for train, test in skf.split(X, y):
    print(train, test)

[ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] [0 1 2 3]
[ 0  1  2  3  6  9 10 11 12 13 14 15 16 17 18 19] [4 5 7 8]
[ 0  1  2  3  4  5  7  8 12 13 14 15 16 17 18 19] [ 6  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11 16 17 18 19] [12 13 14 15]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15] [16 17 18 19]


In [ ]:
# ShuffleSplit с разбиением на 10 блоков

ss = ShuffleSplit(n_splits=10)

for train, test in ss.split(X, y):
    print(train, test)

[ 2  8 16 10 19  7  0  1 14  3  9  5 11 12 18 17  6  4] [15 13]
[10  1 11  8  2  0 15 14  5  4  3 13 16 12 18 17  9  6] [ 7 19]
[ 6  8  0 18 16 11 12 17  9 19  3 14  7  4 10  1  2 13] [15  5]
[14  2 17 18  8  7 10  4  1  5 19 16  3 13 15 12 11  0] [9 6]
[14 12 11 19  9  4 15  8  1 18  7  2 16  3  0  5 10  6] [17 13]
[19 15  0  4  3 10  2 16 18 13 12 17  8  9  1 11  5  6] [ 7 14]
[ 5 14  3 19 10 17 11 16 13 18  1  4  2  8 12  6  7 15] [9 0]
[16  6  0 17 11 18  2  8 10 12 19 13  4  7  3  5 14  1] [ 9 15]
[11  0  8  2 13  5 14 17  7  9  6 12 19  4 18 15 10  3] [ 1 16]
[ 8  3 10 16  1  6  5 19 12 18  0  7 17  4 15 13  9 14] [ 2 11]


In [ ]:
# StratifiedShuffleSplit с разбиением на 10 блоков
# for more details: https://www.kaggle.com/code/viswanathanc/stratifiedshufflesplit-working-with-less-data/notebook

sss = StratifiedShuffleSplit(n_splits=10)

for train, test in sss.split(X, y):
    print(train, test)

[15 19  1 13  5 14  6  0  7  3  8 16  4 17 12 11  9  2] [18 10]
[ 5  8 13  4 15  0 12  9  3 11 19  1 10 18  6 16  7 17] [ 2 14]
[ 8  0  2  5  3 13 11 17  7  9  4  6 10 14 18 12 16  1] [19 15]
[11  6 18  9 16 15  5 12  0 13  2  1 10 17 14  8 19  3] [4 7]
[18 14  7  3  2 10  8 19  9  0 15  1 12  5  6 16 11 13] [ 4 17]
[ 4  3 17  7  0 14 18 19 12  9  8  6 16  5 15  1 13 11] [ 2 10]
[ 5 18 15 13  9  7 10  1 19 11 17  4 12 14  8 16  0  6] [3 2]
[ 5 10 16 19  2 17  1  4  9 13  0 11 15 18  7  8  6 14] [12  3]
[18  2  3 17  8 16 10  6 13  1 19  5 12 15  0  9 14 11] [7 4]
[12  4 10 15 16 14  3 11  2  7 17 18 19  8  0  5  1  9] [13  6]


In [ ]:
# LeaveOneOut

loo = LeaveOneOut()

for train, test in loo.split(X, y):
    print(train, test)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] [0]
[ 0  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] [1]
[ 0  1  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] [2]
[ 0  1  2  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] [3]
[ 0  1  2  3  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] [4]
[ 0  1  2  3  4  6  7  8  9 10 11 12 13 14 15 16 17 18 19] [5]
[ 0  1  2  3  4  5  7  8  9 10 11 12 13 14 15 16 17 18 19] [6]
[ 0  1  2  3  4  5  6  8  9 10 11 12 13 14 15 16 17 18 19] [7]
[ 0  1  2  3  4  5  6  7  9 10 11 12 13 14 15 16 17 18 19] [8]
[ 0  1  2  3  4  5  6  7  8 10 11 12 13 14 15 16 17 18 19] [9]
[ 0  1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19] [10]
[ 0  1  2  3  4  5  6  7  8  9 10 12 13 14 15 16 17 18 19] [11]
[ 0  1  2  3  4  5  6  7  8  9 10 11 13 14 15 16 17 18 19] [12]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 14 15 16 17 18 19] [13]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 15 16 17 18 19] [14]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 16 1

### Выводы:

_**<u>внимание</u>**: кажется, что в русском языке слово «fold» обозначается либо «складка», либо «сгиб» взаимозаменяемо._

#### `shuffle=True` и `shuffle=False`
* Если `shuffle=True`, все данные сначала перемешиваются, а затем разбиваются на K-Folds.
* Если наши параметры зависят от перетасовки, это означает, что наш выбор параметров очень нестабилен.
* Перемешивание в основном полезно, если наши данные отсортированы по классам, потому что тогда каждая складка может содержать образцы только из одного класса.

#### `shuffle=True` vs `shuffle=False`
* If `shuffle=True`, the whole data is first shuffled and then split into the K-Folds.
* If our parameters depend on shuffling, this means our parameter selection is very unstable.
* Shuffle is mainly useful if our data is sorted by classes, because then each fold might contain only samples from one class.

---

#### Что такое «Stratified»?
* Стратифицированная перекрёстная проверка (кросс-проверка) — когда мы разделяем наши данные на складки, мы хотим убедиться, что каждая складка является хорошим представителем всех данных. Самый простой пример: нам нужна одинаковая пропорция разных классов в каждой складке.

#### What is "Stratified"?
* Stratified Cross Validation — when we split our data into folds, we want to make sure that each fold is a good representative of the whole data. The most basic example is that we want the same proportion of different classes in each fold.

---

#### KFold и StratifiedKFold
* KFold — это кросс-валидатор, который делит набор данных на k сгибов.
* Стратификация гарантирует, что каждая складка набора данных имеет одинаковую долю наблюдений в каждой сгибе.
* Другими словами, StratifiedKFold — это улучшенная версия KFold.
* Мы должны предпочесть StratifiedKFold, а не KFold, когда имеем дело с задачами классификации с несбалансированным распределением классов.
* В задачах классификации используется StratifiedKFold, а в задачах регрессии — Kfold.
* В KFold, когда k = n (количество наблюдений), перекрестная проверка KFold эквивалентна перекрестной проверке LeaveOneOut.

#### KFold vs StratifiedKFold
* KFold is a cross-validator that divides the dataset into k folds.
* Stratified is to ensure that each fold of dataset has the same proportion of observations in each fold.
* In other words, StratifiedKFold is the improved version of KFold.
* We should prefer StratifiedKFold over KFold when dealing with classification tasks with imbalanced class distributions.
* Classification tasks use StratifiedKFold, while regression tasks use Kfold.
* In KFold, When k = n (the number of observations), KFold cross-validation is equivalent to LeaveOneOut cross-validation.

---

#### KFold и ShuffleSplit
* KFold разделит наш набор данных на заданное количество сгибов. Складка — это подмножество вашего набора данных.
* ShuffleSplit будет случайным образом выбирать весь наш набор данных во время каждой итерации для создания обучающего набора и тестового набора.
* Параметры `test_size` и `train_size` определяют, насколько большим должен быть набор тестов и обучающих тестов для каждой итерации.
* ShuffleSplit работает итеративно, KFold просто делит набор данных на k сгибов.

#### KFold vs ShuffleSplit
* KFold will divide our data set into prespecified number of folds. A fold is a subset of your dataset.
* ShuffleSplit will randomly sample our entire dataset during each iteration to generate a training set and a test set. 
* The `test_size` and `train_size` parameters control how large the test and training test set should be for each iteration.
* ShuffleSplit works iteratively, KFold just divides the dataset into k folds.