### Многоклассовая классификация. Подбор параметров по сетке

#### Практическое задание для самостоятельного выполнения

**Задание.**

1. Используя инструментарий модуля _**datasets**_, импортировать встроенный набор данных _**iris**_ (часто используется авторами учебников и учебных курсов по машинному обучению в качестве учебного набора данных; содержит информацию о 150 объектах – цветах ириса, которые на основании значений четырех признаков необходимо отнести к одному из трех сортов). <br>Формат команды: `<имя набора данных> = datasets.load_iris()`
* Using the toolkit of the _**datasets**_ module, import the built-in _**iris**_ dataset (often used by authors of textbooks and training courses on machine learning as a training dataset; it contains information about 150 objects - iris flowers, which, based on the values of four features, must be assigned to one of three varieties). Command format: `<dataset name> = datasets.load_iris()`
<br>

2. В результате выполнения п. 1 должен быть создан объект, по структуре подобный словарю. Чтобы убедиться в этом и получить представление о структуре набора данных, вывести наименования ключей набора.
* As a result of step 1, an object similar in structure to a dictionary should be created. To verify this and get an idea about the structure of the data set, display the names of the keys of the set.
<br>

3. Вывести значение ключа DESCR (содержит описание набора данных) и изучить описание набора.
* Print the value of the DESCR key (contains a description of the data set) and examine the description of the set.
<br>

4. Изучить значения остальных ключей и определить ключи, в которых хранятся значения признаков и метки классов. Далее вся работа – только со значениями этих ключей.
* Examine the values of the remaining keys and determine the keys that store feature values and class labels. Further, all the work is only with the values of these keys.
<br>

5. Выполнить разбиение набора данных (значения признаков и метки классов) на обучающую и тестовую выборки в соотношении 70/30.
* Split the data set (feature values and class labels) into training and test samples in the ratio of 70/30.
<br>

6. Создать модель линейной классификации _**SGDClassifier**_ и вывести список доступных параметров модели.
* Create a linear classification model _**SGDClassifier**_ and list the available model parameters.
<br>

7. Создать сетку параметров, включающую 4 вида функции потерь, два типа регуляризаторов, 5 значений коэффициента регуляризации от 0.0001 до 0.001, и число итераций от 5 до 10 с шагом 1.
* Create a parameter grid that includes 4 types of loss function, two types of regularizers, 5 values of the regularization coefficient from 0.0001 to 0.001, and the number of iterations from 5 to 10 with a step of 1.
<br>

8. Создать объект _**GridSearchCV**_, передать ему созданный ранее классификатор и сетку параметров и обучить его. В качестве метрики использовать _**accuracy**_. Предусмотреть вывод времени, затраченного на перебор по сетке (команда %%time).
* Create an object _**GridSearchCV**_, pass it the previously created classifier and parameter grid, and train it. Use _**accuracy**_ as the metric. Provide for the output of the time spent on iterating over the grid (%%time command).
<br>

9. Вывести лучший классификатор, лучший набор параметров и оценку лучшего классификатора в соответствии с заданной метрикой. Получить оценки алгоритма по последним 10 наборам параметров.
* Output the best classifier, the best set of parameters, and the score of the best classifier according to the given metric. Get algorithm scores for the last 10 parameter sets.
<br>

10. Проанализировать полученные результаты, сделать выводы.
* Analyze the results and draw conclusions.
<br>

11. Организовать случайный поиск по сетке. Вывести время, затраченное на случайный перебор.
* Organize a random grid search. Print the time spent on random enumeration.
<br>

12. Вывести те же показатели, что и в п. 9. Сопоставить полученные результаты и время на перебор с результатами, полученными при выполнении п. 9.
* Display the same indicators as in step 9. Compare the results obtained and the time for enumeration with the results obtained when performing step 9.
<br>

13. Сделать выводы, сформулировать рекомендации.
* Draw conclusions and formulate recommendations.

---

1. Используя инструментарий модуля _**datasets**_, импортировать встроенный набор данных _**iris**_ (часто используется авторами учебников и учебных курсов по машинному обучению в качестве учебного набора данных; содержит информацию о 150 объектах – цветах ириса, которые на основании значений четырех признаков необходимо отнести к одному из трех сортов). <br>Формат команды: `<имя набора данных> = datasets.load_iris()`
* Using the toolkit of the _**datasets**_ module, import the built-in _**iris**_ dataset (often used by authors of textbooks and training courses on machine learning as a training dataset; it contains information about 150 objects - iris flowers, which, based on the values of four features, must be assigned to one of three varieties). Command format: `<dataset name> = datasets.load_iris()`

In [ ]:
# import iris flower dataset

from sklearn import datasets

iris = datasets.load_iris()

In [ ]:
# optional: save the iris dataset as a DataFrame

import pandas as pd

iris_df = pd.DataFrame(iris.data)

---

2. В результате выполнения п. 1 должен быть создан объект, по структуре подобный словарю. Чтобы убедиться в этом и получить представление о структуре набора данных, вывести наименования ключей набора.
* As a result of step 1, an object similar in structure to a dictionary should be created. To verify this and get an idea about the structure of the data set, display the names of the keys of the set.

In [ ]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

--- 

3. Вывести значение ключа DESCR (содержит описание набора данных) и изучить описание набора.
* Print the value of the DESCR key (contains a description of the data set) and examine the description of the set.

In [ ]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

---

4. Изучить значения остальных ключей и определить ключи, в которых хранятся значения признаков и метки классов. Далее вся работа – только со значениями этих ключей.
* Examine the values of the remaining keys and determine the keys that store feature values and class labels. Further, all the work is only with the values of these keys.

In [ ]:
# save features and targets from the iris dataset

X = iris.data # features
y = iris.target # targets

display(X, y)

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

The iris flower dataset has following features and target available in it:

Features:
* sepal length in cm
* sepal width in cm
* petal length in cm
* petal width in cm

Targets:
* iris setosa
* iris versicolour
* iris virginica

In [ ]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [ ]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [ ]:
print(iris.data[:5]) # значения признаков / feature values
print(iris.target[:5]) # метки классов / class labels

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0]


---

5. Выполнить разбиение набора данных (значения признаков и метки классов) на обучающую и тестовую выборки в соотношении 70/30.
* Split the data set (feature values and class labels) into training and test samples in the ratio of 70/30.

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

---

6. Создать модель линейной классификации _**SGDClassifier**_ и вывести список доступных параметров модели.
* Create a linear classification model _**SGDClassifier**_ and list the available model parameters.

In [ ]:
# sklearn.linear_model.SGDClassifier  >>  method: get_params()

from sklearn.linear_model import SGDClassifier

sgd = SGDClassifier()
sgd.get_params()

{'alpha': 0.0001,
 'average': False,
 'class_weight': None,
 'early_stopping': False,
 'epsilon': 0.1,
 'eta0': 0.0,
 'fit_intercept': True,
 'l1_ratio': 0.15,
 'learning_rate': 'optimal',
 'loss': 'hinge',
 'max_iter': 1000,
 'n_iter_no_change': 5,
 'n_jobs': None,
 'penalty': 'l2',
 'power_t': 0.5,
 'random_state': None,
 'shuffle': True,
 'tol': 0.001,
 'validation_fraction': 0.1,
 'verbose': 0,
 'warm_start': False}

---

7. Создать сетку параметров, включающую 4 вида функции потерь, два типа регуляризаторов, 5 значений коэффициента регуляризации от 0.0001 до 0.001, и число итераций от 5 до 10 с шагом 1.
* Create a parameter grid that includes 4 types of loss function, two types of regularizers, 5 values of the regularization coefficient from 0.0001 to 0.001, and the number of iterations from 5 to 10 with a step of 1.

In [ ]:
import warnings
from sklearn import metrics
from sklearn.model_selection import GridSearchCV
warnings.filterwarnings("ignore")

# сетка параметров / parameter grid
grid = {'loss' : ['hinge', 'log', 'modified_huber', 'squared_hinge'], 'penalty' : ['l1', 'l2'],
               'alpha' : [0.0001,0.00025,0.0005,0.00075,0.001], 'n_iter_no_change' : [5,6,7,8,9,10]}

---

8. Создать объект _**GridSearchCV**_, передать ему созданный ранее классификатор и сетку параметров и обучить его. В качестве метрики использовать _**accuracy**_. Предусмотреть вывод времени, затраченного на перебор по сетке (команда %%time).
* Create an object _**GridSearchCV**_, pass it the previously created classifier and parameter grid, and train it. Use _**accuracy**_ as the metric. Provide for the output of the time spent on iterating over the grid (%%time command).

In [ ]:
%%time
gs = GridSearchCV(sgd, grid, scoring='accuracy')
gs.fit(X_train, y_train)

Wall time: 3.39 s


GridSearchCV(estimator=SGDClassifier(),
             param_grid={'alpha': [0.0001, 0.00025, 0.0005, 0.00075, 0.001],
                         'loss': ['hinge', 'log', 'modified_huber',
                                  'squared_hinge'],
                         'n_iter_no_change': [5, 6, 7, 8, 9, 10],
                         'penalty': ['l1', 'l2']},
             scoring='accuracy')

---

9. Вывести лучший классификатор, лучший набор параметров и оценку лучшего классификатора в соответствии с заданной метрикой. Получить оценки алгоритма по последним 10 наборам параметров.
* Output the best classifier, the best set of parameters, and the score of the best classifier according to the given metric. Get algorithm scores for the last 10 parameter sets.

In [ ]:
print('лучший классификатор:\n', gs.best_estimator_, '\n') # лучший классификатор
print('набор параметров:\n', gs.best_params_, '\n') # набор параметров
print('оценки на тренировочном наборе:')
print('acc train =', gs.best_score_) # оценка на тренировочном наборе
print('acc test =', metrics.accuracy_score(y_test, gs.predict(X_test)), '\n')
print('оценки алгоритма по последним 10 наборам параметров:\n', gs.cv_results_['mean_test_score'][-10:]) 

лучший классификатор:
 SGDClassifier(alpha=0.0005, loss='modified_huber', n_iter_no_change=9,
              penalty='l1') 

набор параметров:
 {'alpha': 0.0005, 'loss': 'modified_huber', 'n_iter_no_change': 9, 'penalty': 'l1'} 

оценки на тренировочном наборе:
acc train = 0.980952380952381
acc test = 0.9777777777777777 

оценки алгоритма по последним 10 наборам параметров:
 [0.97142857 0.8952381  0.95238095 0.83809524 0.96190476 0.85714286
 0.95238095 0.8952381  0.97142857 0.87619048]


---

10. Проанализировать полученные результаты, сделать выводы.
* Analyze the results and draw conclusions.

> * Точность найденного решения оказалась достаточно хорошей, а на сам перебор по сетки потребовалось меньше 4 секунд, что достаточно быстро, но если взять набор данных из многих тысяч строк, то тут скорее всего перебор займет прилично времени.
>
>
> * The accuracy of the found solution turned out to be quite good, and it took less than 4 seconds to iterate over the grid, which is quite fast, but if you take a dataset of many thousands of rows, then the enumeration will most likely take a decent amount of time.

---

11. Организовать случайный поиск по сетке. Вывести время, затраченное на случайный перебор.
* Organize a random grid search. Print the time spent on random enumeration.

In [ ]:
%%time
from sklearn.model_selection import RandomizedSearchCV

rd = RandomizedSearchCV(sgd, grid, scoring = 'accuracy')
rd.fit(X_train, y_train)

Wall time: 177 ms


RandomizedSearchCV(estimator=SGDClassifier(),
                   param_distributions={'alpha': [0.0001, 0.00025, 0.0005,
                                                  0.00075, 0.001],
                                        'loss': ['hinge', 'log',
                                                 'modified_huber',
                                                 'squared_hinge'],
                                        'n_iter_no_change': [5, 6, 7, 8, 9, 10],
                                        'penalty': ['l1', 'l2']},
                   scoring='accuracy')

---

12. Вывести те же показатели, что и в п. 9. Сопоставить полученные результаты и время на перебор с результатами, полученными при выполнении п. 9.
* Display the same indicators as in step 9. Compare the results obtained and the time for enumeration with the results obtained when performing step 9.

In [ ]:
print('лучший классификатор:\n', rd.best_estimator_, '\n') # лучший классификатор
print('набор параметров:\n', rd.best_params_, '\n') # набор параметров
print('оценки на тренировочном наборе:')
print('acc train =', rd.best_score_) # оценка на тренировочном наборе
print('acc test =', metrics.accuracy_score(y_test, rd.predict(X_test)), '\n')
print('оценки алгоритма по последним 10 наборам параметров:\n', rd.cv_results_['mean_test_score'][-10:]) 

лучший классификатор:
 SGDClassifier(alpha=0.0005, penalty='l1') 

набор параметров:
 {'penalty': 'l1', 'n_iter_no_change': 5, 'loss': 'hinge', 'alpha': 0.0005} 

оценки на тренировочном наборе:
acc train = 0.980952380952381
acc test = 0.9555555555555556 

оценки алгоритма по последним 10 наборам параметров:
 [0.87619048 0.95238095 0.76190476 0.8952381  0.86666667 0.78095238
 0.74285714 0.83809524 0.78095238 0.98095238]


---

13. Сделать выводы, сформулировать рекомендации.
* Draw conclusions and formulate recommendations.

> * Время работы разумеется у случайного перебора меньше, чем у полного, при этом точность оказалась почти на том же уровне, поэтому в данном случае выгоднее будет воспользоваться случайным перебором нежели полным.
>
>
> * Of course, the running time of random enumeration is less than that of complete enumeration, while the accuracy turned out to be almost at the same level, so in this case it would be more profitable to use random enumeration rather than complete enumeration.